kind: pipeline
name: default

steps:
- name: Run rspec
  image: ruby:2.5.3
  commands:
    - bundle
    - bundle exec rspec
  when:
   event:
    - pull_request

- name: Bump and Tag
  image: ruby:2.5.3
  environment:
    GITHUB_API_KEY:
      from_secret: kite_bot_key
  commands:
    - ruby ci/bump.rb
  when:
    event:
      - push
    branch:
      - 1-1-stable
