kind: pipeline
name: default

steps:
- name: Run rspec
  image: ruby:2.6
  commands:
    - bundle
    - bundle exec rspec
  when:
   event:
    - pull_request

- name: Bump and Tag
  image: ruby:2.6
  environment:
    GITHUB_API_KEY:
      from_secret: kite_bot_key
  commands:
    - ruby ci/bump.rb
  when:
    event:
      - push
    branch:
      - 1-1-stable

- name: Publish to RubyGems
  image: ruby:2.6
  environment:
    RUBYGEMS_API_KEY:
      from_secret: rubygems_api_key
  commands:
    - mkdir ~/.gem
    - |
      echo "---\n:rubygems_api_key: $RUBYGEMS_API_KEY" > ~/.gem/credentials
    - chmod 0600 ~/.gem/credentials
    - bundle --jobs $(nproc)
    - bundle exec gem build kite.gemspec
    - bundle exec gem push kite-$DRONE_TAG.gem
  when:
    event:
      - tag
