kind: pipeline
name: default

steps:
- name: Run rspec
  image: ruby:2.6
  commands:
    - bundle
    - bundle exec rspec
  when:
   event:
    - pull_request

- name: Bump and Tag
  image: quay.io/openware/sdk-tools:0.0.6
  environment:
    BRANCH_NAME: ${DRONE_BRANCH}
    REPO_NAME: ${DRONE_REPO}
    GITHUB_API_KEY:
      from_secret: kite_bot_key
  commands:
    - BUNDLE_GEMFILE=/sdk/Gemfile bundle exec rake --rakefile=/sdk/Rakefile release:push
    - BUNDLE_GEMFILE=/sdk/Gemfile bundle exec rake --rakefile=/sdk/Rakefile ci:write_version
  when:
    event:
      - push
    branch:
      - 1-1-stable

- name: Publish to RubyGems
  image: ruby:2.6
  environment:
    RUBYGEMS_API_KEY:
      from_secret: rubygems_api_key
  commands:
    - mkdir ~/.gem
    - |
      echo "---\n:rubygems_api_key: $RUBYGEMS_API_KEY" > ~/.gem/credentials
    - chmod 0600 ~/.gem/credentials
    - bundle --jobs $(nproc)
    - bundle exec gem build kite.gemspec
    - bundle exec gem push kite-$DRONE_TAG.gem
  when:
    event:
      - tag

image_pull_secrets:
  - dockerconfigjson
