sudo: false
language: ruby
rvm:
  - 2.4.0
before_install: gem install bundler -v 1.14.6

env:
  COVERAGE: true

# Execute all of the commands which need to be executed after the build passed.
after_success: ruby ci/bump.rb
