default: &default
  # Note that region formats differ between GCP, AWS and AliCloud
  region:             "europe-west4"
  zone:               "europe-west4-c"
  gcp:
    project:          "helios-devel"
    service_account:  "~/safe/helios-devel.json"
    bucket_name:      "kite-state-helios-devel"
  aws:
    access_key:       "********************"
    secret_key:       "****************************************"
    bucket_name:      "kite-state-helios-devel"
  ali:
    access_key:       "********************"
    secret_key:       "****************************************"
  baremetal:          {}
