# Groups
- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/uaa/scim?/groups?
  value: { }
    # sysops: For automation stuff

# Users
- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/uaa/scim?/users?
  value: [ ]
    # - email: sysops@example.com
    #   password: changeme
    #   name: sysops
    #   firstName: Sys
    #   lastName: Ops
    #   origin: uaa
    #   groups:
    #     - sysops

# OAuth clients
- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/uaa/clients?
  value: { }
    # some-app:
    #   app-icon: 0000000000000000000000000000000000000000000000000000000000000000
    #   app-launch-url: http://myapppage.com
    #   authorities: test_resource.test_action
    #   authorized-grant-types: authorization_code,client_credentials,refresh_token
    #   autoapprove:
    #     - test_resource.test_action
    #     - test_resource.other_action
    #   id: app
    #   override: true
    #   redirect-uri: http://login.example.com
    #   scope: test_resource.test_action,test_resource.other_action
    #   secret: app-secret
    #   show-on-homepage: true

# UAA theming
- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/login/branding?
  value: { }
    # banner:
    #   backgroundColor: "#eeeeee"
    #   link: "https://example.com/logo.png"
    #   text: "Hello!"
    #   textColor: "#333333"
    # company_name: "Company Name"
    # footer_legal_text: "© 2017. Company Name. All right reserved."

# Email notifications
- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/login/smtp?
  value: { }
    # auth: false
    # from_address: hello@example.com
    # host: localhost
    # port: 2525
    # starttls: false
